magaz:
  service:
    catalogue:
      uri: http://localhost:8081
      registration-id: keycloak
spring:
  logging:
    level:
      root: info
      org.springframework.security: DEBUG
      org.springframework.web: DEBUG
      ru.sergalas.magaz: DEBUG
  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: http://localhost:28080/realms/selmag
            user-name-attribute: preferred_username
        registration:
          keycloak:
            client-id: manager-app
            client-secret: wTB0L3nUbacYishOMzfpsRmK9R89ijnO
            scope:
              - openid
              - view_catalogue
              - edit_catalogue
              - microprofile-jwt
            redirect-uri: "{baseUrl}/login/oauth2/code/keycloak"
            authorization-grant-type: authorization_code
server:
  port: 8082