server:
  port: 8086
spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:28080/realms/selmag
      client:
        provider:
          keycloak:
            issuer-uri: http://localhost:28080/realms/selmag
        registration:
          keycloak:
            authorization-grant-type: client_credentials
            scope:
              - metrics
            client-id: admin-service
            client-secret: i0czoqFpFYBcNKcoYPhgOaqAKVQmjgOa
          login:
            provider: keycloak
            scope:
              - metrics
              - openid
            client-id: admin-service
            client-secret: i0czoqFpFYBcNKcoYPhgOaqAKVQmjgOa