server:
  port: 8081
spring:
  security:
    user:
      name: catalogue
      password: '{noop}password'
      roles:
        - SERVICE
  datasource:
    url: jdbc:postgresql://localhost:54325/selpo
    username: postgres
    password: postgres
  flyway:
    schemas:
      - public
      - catalogue
  jpa:
    show-sql: true
logging:
  level:
    sql: info