server:
  port: 8081
spring:
  datasource:
    url: jdbc:postgresql://localhost:54325/selpo
    username: postgres
    password: postgres
  flyway:
    schemas:
      - public
      - catalogue
  jpa:
    show-sql: true
logging:
  level:
    sql: info