server:
  port: 8084
spring:
  boot:
    admin:
      client:
        url: http://localhost:8086
        instance:
          name: feedback-service
          service-host-type: ip
        enabled: true
  data:
    mongodb:
      host: localhost
      port: 8085
      database: feedback
      username: root
      password: example
      authentication-database: admin
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:28080/realms/selmag
      client:
        provider:
          keycloak:
            issuer-uri: http://localhost:28080/realms/selmag
        registration:
          keycloak:
            client-id: feedback-metrics-client
            client-secret: 1qIKlTtW9O9SaqFnkw6ymox5DCavsI5A
            authorization-grant-type: client_credentials
            scope:
              - metrics_server
logging:
  level:
    sql: info
    org.springframework.web: DEBUG
    ru.sergalas.magaz: DEBUG
springdoc:
  swagger-ui:
    oauth:
      client-id: feedback-service-swagger-ui
      use-pkce-with-authorization-code-grant: true
  default-consumes-media-type: application/json
  model-and-view-allowed: false
  show-oauth2-endpoints: true
  ignored-parameter-types:
    - org.springframework.security.core.annotation.AuthenticationPrincipal
    - reactor.core.publisher.Mono
keycloak:
  uri: http://localhost:28080
management:
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"